spring.application.name=smart-poss

# Removed the ':' at the end and added retryWrites for better stability
spring.data.mongodb.uri=mongodb+srv://aarsh:adminposs@cluster0.7czlnw7.mongodb.net/smart_poss_db?appName=Cluster0
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreplysmartposs@gmail.com
spring.mail.password=mhpqoqagkdvpufze
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=true

# Twilio Credentials
twilio.account_sid=AC64c255f18cc5a02e221a4927fcd76cbc
twilio.auth_token=e706b623fa8dea400bc17d12abea6d4a
twilio.whatsapp_number=whatsapp:+14155238886